### ISSUE TITLE
Display Sales channel icon with Order name 

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#191]
## What is the motivation for adding/enhancing this feature?
Currently, the app does not display the sales channel icon alongside the order name. Including the sales channel icon with the order name provides users with valuable visual cues, allowing them to quickly identify the source or channel through which the order was received.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
How many channels do we have to support? Where will we get channel identification type? For example, how will we know that Shopify is an eCommerce channel?

**Comment by Dhiraj1405** [comment]
Closing as not required
