### ISSUE TITLE
Implement notifications 

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#266]
Refer this [feature request]( https://github.com/hotwax/dxp-components/issues/124). 

For this app, we will need notifications for: 

1. New orders.
2. Pending in progress orders. 
3. Pending ready to be shipped orders.

**Comment by ymaheshwari1** [comment]
Closing as we have implemented open order notification in fulfillment app in https://github.com/hotwax/fulfillment/pull/584, and we will implement the above mentioned notifications when required.
