### ISSUE TITLE
Reduce Clutter of Buttons on Order Shipment Card on the Completed page

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#271]
## What is the motivation for adding/enhancing this feature?
The order shipment card contains an excessive number of buttons, leading to a cluttered and potentially confusing user interface.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Please image for reference: 
<img width="1093" alt="Screenshot 2023-09-21 at 6 05 19 PM" src="https://github.com/hotwax/fulfillment-pwa/assets/119936391/e786fd78-fcec-42c1-a613-91efeceb1ac6">

**Comment by divyanshmangal** [comment]
can you assign this issue to me

**Comment by k2maan** [comment]
Sure @divyanshmangal go ahead

**Comment by Deven-ai12** [comment]
can you assign this issue to me

**Comment by k2maan** [comment]
@Deven-ai12 please find another issue, this is already assigned

**Comment by Dhiraj1405** [comment]
In the new UI, the clutter is already managed.
