### ISSUE TITLE
Improve UI for Order Box and Issue Reporting Buttons

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#304]
## What is the motivation for adding/enhancing this feature?
The buttons for Order Box and Issue Reporting are displayed within the same segment, leading to confusion among users. This layout makes it challenging for users to distinguish between the two functionalities. 

## What are the acceptance criteria?
Improve the user interface by separating the buttons for Order Box and Issue Reporting. Providing a clearer visual distinction between these functions will enhance user experience and reduce confusion.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Refer this UI: https://www.figma.com/file/wK5FMs4z2zXQR9VfHV9ycE/Dhiraj's-Ionic-6-Material-UI-Kit-(Community)?type=design&node-id=28867%3A152486&mode=design&t=TRefPw85hfMzAOD5-1

**Comment by dt2patel** [comment]
closed due to new rejection UI being rolled out
