### ISSUE TITLE
Add Tracking Codes to Orders Manually

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#305]
On the order details page, allow users to enter tracking codes manually from the Shipment method and Carrier card. UI image included below:

https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=40160-85233&t=q2XYsB5qoahzbDzh-4

![Image](https://github.com/user-attachments/assets/88ac84f9-0621-4f7f-8f85-154ca330ed64)

![Image](https://github.com/user-attachments/assets/1a9a1201-d54a-4d82-9a17-fab46691ec19)

![Image](https://github.com/user-attachments/assets/453624bc-4cfa-4283-85c9-9712442ff60c)

**Comment by dt2patel** [comment]
not the most relevant feature. But we do want to add option to manually add tracking code to an order

**Comment by Adameddy26** [comment]
Verified the changes and working fine in release v2.8.0. Hence, closing this ticket.
