### ISSUE TITLE
Show Error Message Received from Shipping Carrier when Generating Shipping Label

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#344]
## What is the motivation for adding/enhancing this feature?
Currently, when users attempt to generate a shipping label, there are instances where they encounter error messages from the shipping carrier. While these messages is not in a user friendly format, they lack detailed information that could help users understand the issue better. 

## What are the acceptance criteria?
When users encounter an error, the system should provide detailed and user-friendly error messages.

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
@Adameddy26 please create a test case document for this and then find the exact scenarios where this is failing.

**Comment by Dhiraj1405** [comment]
The ticket should be created in backend because the values are fetched from there.
