### ISSUE TITLE
Unable to select `none` as product store on settings page

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment#367]
## Current behavior

When selecting `none` as product store, the store does not gets updated and the previous store is again selected.

## Expected behavior

User should be able to select `none` as product store.

## Steps to reproduce the issue

- Go to settings page
- Select `None` in product store option
- Move to any other page and then again return to settings page
- Verify that `None` is not selected and the previous store is selected

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version: 

## Additional information

The issue is due to the check on https://github.com/hotwax/fulfillment-pwa/blob/main/src/views/Settings.vue#L522

**Comment by dt2patel** [comment]
I am not sure if user should be able to select none as an option during fulfillment process. When would user need to be completely independent of a product store for fulfillment? @ymaheshwari1

**Comment by ymaheshwari1** [comment]
> I am not sure if user should be able to select none as an option during fulfillment process. When would user need to be completely independent of a product store for fulfillment? @ymaheshwari1

I just created this as the option for the `None` is available for selection. But it makes sense that there is no need to have `None` option for product store.

**Comment by ymaheshwari1** [comment]
We have concluded that we will remove the none option from the productStore selector.

**Comment by Adameddy26** [comment]
Verified it in release v2.6.0 and found that this option of 'none' is now deprecated from the product store selection dropdown. Hence, closing this ticket.
