### ISSUE TITLE
Pack Orders popup on `In Progress` tab - checkbox placement

### ISSUE THREAD

**Issue by sanjanashrivastava** [hotwax/fulfillment#403]
## What is the motivation for adding/enhancing this feature?

In the app in `In progress` tab on clicking `Pack orders` this popup appears. It's UI is different from figma and needs to be updated according to the figma file. Please refer to the attached images for clarity. 
Current version: 
<img width="294" alt="Fulfillment app - pack orders on in progress page - current" src="https://github.com/hotwax/fulfillment-pwa/assets/155512107/82749228-7831-483e-89e2-d429c8e562b0">

## What are the acceptance criteria?

Checkbox and label placement needs to be reversed. Please refer to the figma file as well as attached image for reference. Correct the UI accordingly. 
Required updated version: 
<img width="409" alt="Fulfillment app - pack orders on `in progress` page - expected UI" src="https://github.com/hotwax/fulfillment-pwa/assets/155512107/44be5570-8975-4c8b-a189-ae4b4f522b6b">

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
won't fix
