### ISSUE TITLE
Continous loading occurs on UI when user packs the different order after first attempt.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#411]
## Current behavior
Continous loading occurs on UI when user packs the different order after first attempt.

## Expected behavior
Continous loading should not occur on UI when user packs the different order after first attempt.

## Steps to reproduce the issue
Open the UAT environment of App.
Pack one order.
Now take different order and pack it too.
Go back to fulfillment app tab and observe the issue.

## Environment details
- App version: v1.23.0
- Environment: UAT

## Additional information
https://jam.dev/c/1ba63220-ec5c-4988-904b-ea2760e7013b

**Comment by dt2patel** [comment]
@Adameddy26 I think the video you linked does not fully show the steps to reproduce, it would be more helpful if you could include the full cycle so that dev can see what triggered the issue.

**Comment by Adameddy26** [comment]
> @Adameddy26 I think the video you linked does not fully show the steps to reproduce, it would be more helpful if you could include the full cycle so that dev can see what triggered the issue.

Done

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.8.1. Hence, closing this ticket.
