### ISSUE TITLE
Order Card Not Removing from UI Upon Unpacking Order in Completed Tab.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#416]
## Current behavior
Upon unpacking an order from the Completed tab, the corresponding order card remains visible in the UI instead to moving to 'In Progress' tab.

## Expected behavior
Upon unpacking an order from the Completed tab, the corresponding order card should be promptly removed from the UI to reflect the updated status of the order.

## Description 
When a user unpacks an order from the Completed tab, the corresponding order card remains visible in the user interface (UI) instead of being removed as expected. This issue impacts the user experience by causing confusion and clutter in the UI, as users may believe that the order is still pending or completed, leading to potential errors or oversight in managing orders.

## Steps to Reproduce - 
Open the App in UAT environment and then navigate to the completed tab in the UI.
Identify a completed order.
Attempt to unpack the completed order.
Observe that the order card remains visible in the UI instead of being removed as expected.

## Environment details
- App version: v1.23.1
- Environment: UAT
- OMS instance : dev-oms

## Additional information
https://jam.dev/c/faf0ac59-51ef-43b7-a491-28a2de5d966f

**Comment by amansinghbais** [comment]
When unpacking an order the API runs too fast and the solr index does not update resulting in having the current unpacked order in the completed section.

Currently we don't have any solution for above problem. Hence closing this issue.

**Comment by Dhiraj1405** [comment]
We will recreate this issue, as there seems to be no possible solution for this and also it is not currently a blocker.
