### ISSUE TITLE
Disappearance of '0' in Transfer Order Item Quantity Field Upon Removal and Clicking Outside

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#421]
## Note
This issue can be fixed for receiving app too.

## Current behavior
After removing the '0' from the quantity field and clicking outside, the '0' does not reappear, leaving the quantity field blank.

## Expected behavior
Upon removal of the '0' from the quantity field and clicking outside, the '0' should reappear in the quantity field, indicating a quantity of zero for the respective item.

## Steps to reproduce the issue
Navigate to a transfer order section and open any PO.
Remove the '0' from the quantity field.
Click outside the quantity field to confirm the removal.
Observe that the '0' does not reappear in the quantity field.

## Environment details
- App version: TRANSFER-ORDER-UI-D9CDF5B 
- App environment: UAT

## Additional information
https://jam.dev/c/478b7a03-8cb1-47db-b4b6-594853439084

**Comment by dt2patel** [comment]
Behavior does not impact user in any meaningful way. Closing task
