### ISSUE TITLE
Incorrect redirection on order packing.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#441]
## Expected behavior
Upon packing an order, the user should be directed to the shipping label or packing slip tab within the current session.

## Steps to reproduce the issue
Log in to the App having view app permission.
Go to In progress tab and select an order to pack.
Initiate the packing process.
Observe the redirection behavior.

## Environment details
App Version: V2.0.1
Testing Environment: UAT

## Additional information
https://jam.dev/c/6eafb980-e119-4882-8123-0b7483e4afaa

**Comment by ymaheshwari1** [comment]
@Adameddy26 Please verify this, its already in production and was part of https://github.com/hotwax/fulfillment/releases/tag/v2.0.2

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.10.4. Hence, closing this ticket.
