### ISSUE TITLE
Translation Error: "Gateway" in payment method is not appearing translated in spanish on order details page.

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#446]
## Expected behavior
The term "Gateway" should be translated into Spanish on the order details page for users with Spanish language preference.

## Environment details
App Version: V2.0.1
Testing Environment: UAT

## Additional information
[es (1) (1).json](https://github.com/hotwax/fulfillment-pwa/files/14567460/es.1.1.json)

**Comment by Adameddy26** [comment]
Can't verify this issue in v2.0.3. Currently language changes are not getting saved and page is not getting translated in spanish. 
https://jam.dev/c/0833cb27-e2a6-4b1e-acde-5315dce41239

Hence, reopening it.

**Comment by amansinghbais** [comment]
This issue if fixed properly. The language switcher stopped working since dxp-component is using ionic 7 while our app is on ionic 6. 

This will fix when we will update our app to ionic v7.6.0. The following PR is created for this migration: https://agithub.com/hotwax/fulfillment-pwa/pull/458

**Comment by Adameddy26** [comment]
Verified and working fine release v2.0.3. Hence, closing it.
![Screenshot from 2024-06-27 19-19-02](https://github.com/hotwax/fulfillment/assets/158989293/d39514fe-ba3b-4554-ada8-b3f600950896)
