### ISSUE TITLE
Update button labels: Print Picksheet and Print Picklist

### ISSUE THREAD

**Issue by Shreyaakothari** [hotwax/fulfillment#460]
## Current behavior

Currently, within the Pick tab of the fulfillment app, there's a button labeled "Print Picksheet," which generates a list of order items to be picked. Similarly, in the Pack tab, there's a button labeled "Print Picklist" which allows reprinting the initially generated picklist.

The discrepancy in labeling might lead to confusion for users. To ensure clarity and consistency throughout the app, it is proposed to standardize the labeling of these buttons.

## Expected behavior

Rename the button labeled "Print Picksheet" in the Pick tab to "Print Picklist" for consistency with the terminology used in the Pack tab.

Rename the button labeled "Print Picklist" in the Pack tab to "Reprint Picklist" to accurately reflect the action of reprinting the picklist.

## Environment details

Testing Environment: UAT
App version: V2.0.2

**Comment by ymaheshwari1** [comment]
Discussed, we will rename the `Print Picksheet` to `Print Picklist` to have consistency in the labels, but we will not make the button label to `Reprint Picklist` on the pack tab.

**Comment by ymaheshwari1** [comment]
@Ridwan6947 Pick this one, once your in hand task is completed.

**Comment by ymaheshwari1** [comment]
> [@Ridwan6947](https://github.com/Ridwan6947) Pick this one, once your in hand task is completed.

@Ridwan6947

**Comment by Ridwan6947** [comment]
@ymaheshwari1

**Comment by Adameddy26** [comment]
Verified in release v2.7.2 and found that required changes are not done.
Hence, reopening this ticket.
![Screenshot from 2024-08-06 10-49-59](https://github.com/user-attachments/assets/8cb6d7a0-23f1-4971-8791-e0ca635ea6b5)

**Comment by ymaheshwari1** [comment]
@Adameddy26 The issue has been fixed in release 2.7.2, but the uat is deployed on 2.5.5 tag thus the changes are not available on uat. You can verify the changes on dev.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.2.
Hence,closing this ticket.
