### ISSUE TITLE
Improve Visual Feedback and Mapping Selection in Shipped Orders Section

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#474]
## Description
Currently, in the Shipped Orders section, newly created order mappings are not appearing as selected when users create them. Instead, the last active mapping is displayed as selected, potentially causing confusion regarding which mapping is currently active. Furthermore, there is no visual indication to differentiate between active and inactive mappings, which can lead to user uncertainty and difficulty in identifying the currently selected mapping.

## Additional Information
https://jam.dev/c/229b2914-8854-497c-8fba-e04b749c96db

**Comment by Dhiraj1405** [comment]
Not required for now, will recreate when needed.
