### ISSUE TITLE
'Order ID' field option appears highlighted unnecessarily and Save button color appears disabled in Import Shipped Orders CSV mapping

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#477]
## Expected behavior
Only the selected field option should be highlighted in the import shipped orders CSV mapping interface, providing clear visual feedback to the user about their selection. Additionally, the save button should have a color that clearly indicates its active status, ensuring users recognize it as functional.

## Steps to reproduce the issue
1. Open the import shipped orders CSV mapping interface.
2. Observe the 'Order ID' field option, which appears highlighted by default.
3. Attempt to select a different field option for mapping.
4. Notice that the 'Order ID' field option remains highlighted even when another option is selected.
5. Observe the save button's color, which may resemble that of a disabled button.

## Environment details
App version : MAIN-F2FA0F7
App testing environment : DEV

## Additional information
https://jam.dev/c/5caaa9b8-a92d-4efb-b15b-23885bfee358

**Comment by R-Sourabh** [comment]
The issue of the default highlight on the first option in the 'Order ID' mapping is not appearing, and the issue of the option remaining highlighted even when another option is selected is also not occurring.

**Comment by ymaheshwari1** [comment]
The button being of gray(medium) color is a pattern that has being followed across apps on file upload pages, thus there is no need to change its color here, hence closing the related PR(https://github.com/hotwax/fulfillment/pull/844).

**Comment by ymaheshwari1** [comment]
@Adameddy26 Please verify the issue of the option being highlighted and if everything works as expected, please close this issue.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.10.4. Hence, closing this issue.
