### ISSUE TITLE
Add permissions support for rejection reasons

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment#502]
## What are the acceptance criteria?

- [ ] Create permission for each rejection reason with id `<REJ_ENUM_ID>_VIEW`
- [ ] Add support to link/unlink security groups for that permission

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by dt2patel** [comment]
Closing this ticket since this version of the implementation is no longer moving forward. Will consider alternate options
