### ISSUE TITLE
 Automate Rejection of Multiple Brokered Items in Orders with Partial Rejections

### ISSUE THREAD

**Issue by Dhiraj1405** [hotwax/fulfillment#513]
## What is the motivation for adding/enhancing this feature?
Currently, when a multi-item order is brokered to a store location and one item is rejected, the remaining item(s) may still be shipped, leading to unnecessary split shipments. To streamline the process and avoid potential issues with split shipments, we propose automating the rejection of the remaining brokered item(s) when one item is rejected. This automation will ensure that the entire order can be rebrokered to a single location without manual intervention.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Dhiraj1405** [comment]
Client quote: 

```
Currently, when a multi item order is brokered to a store location, they are able to reject 1 item and still ship the other(s). This risks creating unnecessary split shipments, so we are asking stores to reject the other item(s) and leveraging a rejection reason that does not impact ATP. This way, the entire order can attempt to be rebrokered to a single location.

We would like to automate this process so that when one item from a an order containing multiple items brokered to the same location is rejected, the other brokered item(s) can be automatically rejected (without zeroing out ATP/without human action required).
```

**Comment by ravilodhi** [comment]
Covered under - https://github.com/hotwax/fulfillment/issues/640. Hence closing this ticket.
