### ISSUE TITLE
Ensure Proper Overlay Behavior for Side Menus

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#547]
## Description
Currently, when one side menu is open on the page, and the other side menu is triggered, the first menu does not overlay properly with the central part of the page. This results in a poor user experience as the side menus overlap incorrectly or do not display as intended.

## Additional information
https://jam.dev/c/4edf1567-b635-482c-9312-faaa18a72358

**Comment by dt2patel** [comment]
This is expected ionic behavior, we won't be solving this for now. @ymaheshwari1 do you agree?

**Comment by ymaheshwari1** [comment]
> This is expected ionic behavior, we won't be solving this for now. @ymaheshwari1 do you agree?

Yes, we will not be fixing it right away, but in job-manager we have added css to make the background transparent for this case.

**Comment by dt2patel** [comment]
I believe we've made it so that the back drop doesn't show up.

**Comment by Dhiraj1405** [comment]
As I can see the discussion here, we will not be moving in the direction of writing any custom CSS, so I am closing it for now.
