### ISSUE TITLE
Update UI for kit products

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment#565]
## Current behavior

Currently the UI for kit products is distorted.

## Expected behavior

UI should be consistent

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by dt2patel** [comment]
Added new UI for Kit Products and Service products workflow:

https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=37688-117375&t=bcweOHxcg24YIdhq-11

Lets discuss and proceed

**Comment by ravilodhi** [comment]
The update kit product UI is handled in the following ticket - https://github.com/hotwax/fulfillment/issues/603
So closing this ticket.
