### ISSUE TITLE
Previous picker gets removed when adding a new picker in the picklist

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment#570]
## Current behavior

When editing a new picker to an already existing pickers, the previously associated picker gets removed. This happens only when we have a single picker assigned to a picklist. If we have multiple pickers then it works fine.

## Expected behavior

Previous picker should not be removed from the list.

## Steps to reproduce the issue

- Go to in-progresss page
- Select a picklist having a single picker assigned
- Click edit picker button and add a new picker
- Verify that the previously associated picker is removed from the picklist

## Can you handle fixing this bug by yourself?

- [x] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.5.0. Hence, closing it.
