### ISSUE TITLE
Manage single and full order rejection

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment#572]
## What is the motivation for adding/enhancing this feature?

Retailers toggle between single item and full shipment rejection to avoid unnecessary splits. There is a new rejection api available for this that we also need support. Will discuss more internally about that.

https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=37688-117375&t=MyRJFBieR7ZnfiDc-11

**Comment by ravilodhi** [comment]
Added OMS settings on settings page to control partial/full order rejection. By default full order rejection is enabled.

![Partial_Order_Rejection_Settings](https://github.com/user-attachments/assets/a6162e0d-8e59-4fcc-a837-5de2ea366d51)

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.7.2. Hence, closing it.
