### ISSUE TITLE
Custom mapping field for Packed Order CSV

### ISSUE THREAD

**Issue by Nishtha-Jain-1119** [hotwax/fulfillment#575]
As per the client requirement:

There is a need for a new field that will the concatenation of these previous fields.
New_Field: State + City.

This sample csv and exel sheet is provided by the client for mapping.
[sample_data_for_sagawa.csv](https://github.com/user-attachments/files/15545520/sample_data_for_sagawa.csv)
https://docs.google.com/spreadsheets/d/1fgakt8NOyGbAd4YRkpFQqistwu-EESFgP7f5Xzj19xI/edit?usp=sharing

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.5.0. Hence, closing it.
