### ISSUE TITLE
Generate Shipping Label from pdf url

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#578]
## What is the motivation for adding/enhancing this feature?
Shipping Label generation in ShipHawk returns pdf url instead of label image. So modify the current workflow mainly to render the label pdf directly if ShipmentPackageRouteSegment.labelImageUrl contains a pdf url instead of calling ShippingLabel.pdf endpoint to construct a pdf from label image.

## What are the acceptance criteria?
If ShipmentPackageRouteSegment.labelImageUrl field contains a pdf url then it should be opened in a new tab on click of generate/regenerate shipping label button.

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v2.5.0. Hence, closing it.
