### ISSUE TITLE
Create shipment for Transfer Order failed if there are multiple order items with the same product

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#579]
## Current behavior
Create shipment for Transfer Order failed if there are multiple order items with the same product.

## Expected behavior
Create shipment for Transfer Order should work fine even if there are multiple order items with the same product.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.5.0. Hence, closing it.
