### ISSUE TITLE
Empty field for CSV mapping for export packed order

### ISSUE THREAD

**Issue by Nishtha-Jain-1119** [hotwax/fulfillment#586]
## Current behavior

Not able to add empty field in CSV mapping for export packed order in EXIM.

## Expected behavior

There should be the option for adding both new field as empty or with some default value in it.

## Steps to reproduce the issue

Here is the video showing the issue
[59682b0c-fd7b-44b1-8063-1e003f3b3732.webm](https://github.com/hotwax/fulfillment/assets/127538617/a2d82322-e985-41e4-9b8b-81f3f1db9f43)

**Comment by ymaheshwari1** [comment]
Closing as fixed in https://github.com/hotwax/fulfillment/pull/569
