### ISSUE TITLE
Create a new field (Facility State + Facility City)

### ISSUE THREAD

**Issue by ghost** [hotwax/fulfillment#588]
## What is the motivation for adding/enhancing this feature?

Create an additional field (Facility State + Facility City) in the fulfillment app's 'Export packed' orders.
86cvr0q5m

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by ymaheshwari1** [comment]
Handled in https://github.com/hotwax/fulfillment/pull/591

**Comment by ymaheshwari1** [comment]
Closing as already handled, and verified.
