### ISSUE TITLE
New Mapping Button Not Functioning Properly

### ISSUE THREAD

**Issue by Nishtha-Jain-1119** [hotwax/fulfillment#589]
## Current behavior

Sometimes `New Mapping` button doesn't work.

Here is the video showing the issue.
https://jam.dev/c/5b51a146-abc6-4b41-a00c-47450b254866

But it's working for other mapping
https://jam.dev/c/d243347c-753b-4a29-b160-79b21639fcd1

**Comment by ymaheshwari1** [comment]
Already fixed, will be available in upcoming release.

**Comment by ymaheshwari1** [comment]
Closing as verified and fixed.
