### ISSUE TITLE
Update Kit Product UI

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#603]
## What is the motivation for adding/enhancing this feature?
https://docs.hotwax.co/documents/orders/fulfillment/kit-products

https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=37688-117375&t=UINEy0nFrGJ1wVRM-0

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.6.0. Hence, closing this ticket.
@ravilodhi Found that the icon of showing kit components is not getting changed to up arrow on clicking it.

**Comment by ravilodhi** [comment]
@Adameddy26 Thanks for pointing this out. The below PR will handle it - https://github.com/hotwax/fulfillment/pull/667/files

**Comment by Adameddy26** [comment]
Verified the chevron up icon changes and is working fine.
