### ISSUE TITLE
Improve picker fetching logic to use solr doc instead of using performFind

### ISSUE THREAD

**Issue by ymaheshwari1** [hotwax/fulfillment#611]
## What is the motivation for adding/enhancing this feature?

When using performFind call to fetch the information for pickers, its response from the api is taking too long and thus having a bad user experience.

## What are the acceptance criteria?

- [ ] Replace performFind call with solr doc for fetching pickers information

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified the spinner login and found that it is working fine in release v2.6.0.

**Comment by Adameddy26** [comment]
Verified rest of the changes which are merged later and they are working fine in release v2.9.3. Hence, marking this ticket as closed.

**Comment by Adameddy26** [comment]
Issue still exists in edit picker modal. Hence, reopening this issue.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.10.4. Hence, closing it.
