### ISSUE TITLE
Add force scan functionality to the pack button in the order details page

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/fulfillment#612]
## What is the motivation for adding/enhancing this feature?

Allow force scan functionality while packing order from the details page.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Enhancement changes verified in release v2.7.0 and found one issue.
Message showing no orders found is visible when force scan is on and user scrolls down the in progress page to the bottom.

Hence, reopening it.

![Screenshot from 2024-07-24 18-42-14](https://github.com/user-attachments/assets/f88e0590-44c1-4911-b6b6-5d50589426c0)

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.1. Hence, closing it.
