### ISSUE TITLE
Allow store staff to change shipment method and carrier on shipment

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment#624]
## What is the motivation for adding/enhancing this feature?

Once a shipment is initiated, and shown in the packed orders tab, retailers that use multiple carriers want the option to be able to change carrier based on the area where an order is being shipped to. 

On the order detail page there will be a new card that shows the shipping method and the labels generated against a shipment. If the user wants to switch carriers after a label is already generated, the OMS will first try to void the existing label before setting the new carrier and fetching shipping labels for it.

**Comment by dt2patel** [comment]
<img width="1214" alt="Screenshot 2024-07-11 at 5 05 40 PM" src="https://github.com/hotwax/fulfillment/assets/60128132/92b93ca2-9e7e-4943-872f-d0fadb6f7137">

**Comment by Adameddy26** [comment]
Changes verified in release v2.7.0. Issues found are separately raised. Hence, closing this ticket.
