### ISSUE TITLE
Initial Login Force Scan Toggle Issue

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#626]
## Current behavior
At the initial login, when trying to toggle on the Force Scan preference, the toggle does not activate, but a toast message appears saying `Force Scan preference updated successfully`.

## Expected behavior
The Force Scan preference should be toggled on, and the toast message should accurately reflect the successful update.

## Steps to reproduce the issue
1. Log in to the application.
2. Navigate to the settings page.
3. Attempt to toggle on the Force Scan preference.

## App version
v5.2.3

## Additional information
Jam - https://jam.dev/c/cde3de59-3208-4f63-bd27-b5d68d134c4d

**Comment by amansinghbais** [comment]
Following issue is fixed in the following PR: https://github.com/hotwax/fulfillment/pull/614. Hence closing this ticket.
