### ISSUE TITLE
Force Scan Toggle Fails but Can Be Activated with Hold

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#627]
## Current behaviour
When trying to toggle on the Force Scan preference, a toast message appears stating `Failed to update the Force Scan preference` Despite this, holding the toggle allows it to be activated

## Expected behaviour
The Force Scan preference should be toggle on without any error.

## Steps to reproduce the issue
1. Log in to the application.
2. Navigate to the settings/preferences page.
3. Attempt to toggle on the Force Scan preference.
4. Observe the toast message indicating failure.
5. Hold the toggle and attempt to activate it again.

## App version
v5.2.3

## Additional information
Jam: https://jam.dev/c/1bf2dd20-2fb9-4118-8bb2-56c781677620

**Comment by ymaheshwari1** [comment]
Handled already, will be fixed in 2.7.0 release.

**Comment by amansinghbais** [comment]
Handled in following PRs: https://github.com/hotwax/fulfillment/pull/614
https://github.com/hotwax/fulfillment/pull/637
