### ISSUE TITLE
Setting UI for partial rejections and Related Shipment Rejection

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment#640]
## What is the motivation for adding/enhancing this feature?

Partial rejection and related shipment rejection toggle will look like the following:

<img width="941" alt="Screenshot 2024-07-19 at 4 22 20 PM" src="https://github.com/user-attachments/assets/58744ed7-97fb-44f1-865c-3f03e0284390">

**Comment by Adameddy26** [comment]
Changes verified and working fine in release v2.7.0. Hence, closing it.
