### ISSUE TITLE
No Shipping Method Setup Leads to Blank Option in Dropdown on Order Detail Page

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#649]
## Current behavior
A blank option appears in the dropdown, causing confusion and potential errors in order processing.

## Expected behavior
If no shipping method is set up, the dropdown should either display a message such as "No shipping method available" or be disabled to prevent user interaction.

## Steps to reproduce the issue
Navigate to the order detail page of In Progress page.
Select the carrier and then open the shipping method dropdown.
Observe that a blank option is displayed if no shipping method is set up for the selected carrier.

## Environment details
App version : V2.7.0
App environment : UAT

## Additional information
https://jam.dev/c/9077cf41-9619-4ab5-b119-ffef0281f039

**Comment by Dhiraj1405** [comment]
Will add UI here

**Comment by dt2patel** [comment]
@Adameddy26 please review jam video since it doesn't seem to be connected to the issue you mentioned. Need more details

**Comment by dt2patel** [comment]
https://www.figma.com/design/bVPRRw282CqGKMdbz7dciH/HC-Ionic-design-system?node-id=40156-85084&t=q2XYsB5qoahzbDzh-4



![Image](https://github.com/user-attachments/assets/68c03047-1425-4afe-ab08-27a77e878fc6)

Clicking on the information button will link to this doc:
https://docs.hotwax.co/documents/v/system-admins/fulfillment/shipping-methods/carrier-and-shipment-methods

**Comment by Adameddy26** [comment]
> @Adameddy26 please review jam video since it doesn't seem to be connected to the issue you mentioned. Need more details

Corrected the same.

**Comment by Adameddy26** [comment]
Issue verified in release v2.8.0 and found that message 'No shipment methods linked to <carrier>' is not visible when user navigate back to same page after switching the tab/section. Hence, reopening this issue.
https://jam.dev/c/3c63fc24-549d-42f4-aa4f-6dac008e2346

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.8.1. Hence, closing this ticket.
