### ISSUE TITLE
Selected Shipping Method/Carrier Not Saved - Incorrect Shipping Method/Carrier Displayed After Redirection

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#650]
## Current behavior
The previously selected shipping method is displayed instead of the new one.

## Expected behavior
The newly selected shipping method should be displayed correctly after redirection to the same page.

## Steps to reproduce the issue
Login the App with valid user credentials.
Navigate to In Progress page.
Select any order and open its detail page.
Select a shipping method.
Navigate to some other section and then come back to same page for the same order.
Check the shipping method displayed on the page.

## Environment details
App version : v2.7.0
App environment : UAT

## Additional information
https://jam.dev/c/3f2095e3-637c-427e-8ef4-7543e6dbbe0f

**Comment by ravilodhi** [comment]
This has been fixed in the following PR - https://github.com/hotwax/fulfillment/pull/652

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.2. Hence, closing it.
