### ISSUE TITLE
Missing Tracking Code Post-Label Generation Prevents Label Voiding

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#651]
## Current behavior
The tracking code is not visible on the UI after the shipping label is generated. Users cannot void the label due to the absence of the tracking code.

## Expected behavior
The tracking code should be displayed on the UI immediately after the shipping label is generated. Users should be able to view the tracking code and have the option to void the shipping label if necessary.

## Steps to reproduce the issue
Navigate to the order detail page of In Progress order.
Select pre-configured shipping method and carrier and then try to generate the label.
Observe the UI after the label generation process is complete.
Attempt to void the generated shipping label.

## Environment details
App version : v2.7.0
App environment : UAT

## Additional information
https://jam.dev/c/578a1e43-94e7-48a4-ba11-40db9a96102a

**Comment by ravilodhi** [comment]
Fixed under the following PR - https://github.com/hotwax/fulfillment/pull/652

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.2. Hence, closing it.
