### ISSUE TITLE
Unnecessary Horizontal Separation Line at End of Dropdown List Options

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#654]
## Note
Same case exists for box and box type change dropdown in the order card.

## Expected behavior
If there are no further options after the last listed item, no additional separation line should be displayed at the end of the dropdown list.

## Steps to reproduce the issue
Login the app with valid user credentials.
Navigate to in progress tab and click the order reject icon for any order.
Scroll through the available options within the dropdown.
Observe that at the bottom of the dropdown list, a horizontal separation line is present.

## Environment details
App version : v2.7.0
App environment : UAT

## Additional information
![Screenshot from 2024-07-23 18-20-46](https://github.com/user-attachments/assets/05a29074-82e5-4721-933b-5bcadba7735d)

**Comment by Dhiraj1405** [comment]
We will not pick this, as it's not breaking any functionality. Hence closing.
