### ISSUE TITLE
Channel value not showing in order lookup

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment#656]
## Current behavior

The channel value is missing in the order lookup page.

<img width="968" alt="Screenshot 2024-07-24 at 9 57 46 AM" src="https://github.com/user-attachments/assets/88bbb394-be2f-4789-a9d3-45ed6964ee9e">

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.1. Hence, closing this issue.
