### ISSUE TITLE
Add permission check on the Force scan setting

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/fulfillment#664]
## What is the motivation for adding/enhancing this feature?

We should add Common Admin permission over force scan setting in order to allow access to only Super or Admin user.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified it in release v2.7.1 and found that user is able to perform actions on disabled card items though the common admin permission is not given to the user.
Hence, reopening this issue.
https://jam.dev/c/55afe173-a626-41a0-81ed-33442cf028bd

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.2. Hence, closing it.
