### ISSUE TITLE
Shipping label not generated when changing carrier in shipment method card

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#681]
## Current behavior
When changing the carrier in the Shipment Method card from the order details page, the shipping label does not get generated if the shipment method remains the same. This issue affects the workflow by preventing the generation of the correct shipping label after a carrier change.

## Expected behavior
The shipping label should be generated correctly when the carrier is changed in the Shipment Method card, regardless of whether the shipment method is the same

## Steps to reproduce the issue
1. Navigate to the order details page.
2. Change the carrier in the Shipment Method card.
3. Attempt to generate the shipping label.
4. Observe that the shipping label is not generated.

## Can you handle fixing this bug by yourself?
- [ ] YES
- [x] NO

## Environment details
- Browser: Chrome
- OS: IOS, Version 14.4.1
- Code Version: Dev version of the App.

## Additional information
Jam: https://jam.dev/c/15249429-3142-403f-8176-7f12fd5ff9bf

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.7.2. Hence, closing it.
