### ISSUE TITLE
Fulfillment app does not default to correct carrier in shipment method card

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#682]
## Current behavior
If an order has a specified carrier (e.g., Drivin), the Fulfillment app does not default to this carrier in the Shipment Method card. When generating a shipping label, it uses the selected carrier, but if the carrier is changed and then the shipping label is generated, the label generated is the one that was previously generated (e.g., Drivin), leading to inconsistency.

## Expected behavior
The Fulfillment app should default to the correct carrier specified in the order in the Shipment Method 

## Steps to reproduce the issue
1. Create an order in Shopify, import it into OMS, and check the associated carrier.
2. Open the Fulfillment app, check the carrier in the Shipment Method card, and generate the shipping label.
3. Change the carrier and generate the shipping label.
4. Observe that the shipping label generated is still the one that was previously generated (e.g., Drivin).

## Can you handle fixing this bug by yourself?
- [ ] YES
- [x] NO

## Environment details
- Browser: Chrome
- OS: OS, Version 14.4.1
- Code Version: Dev version of the App.

## Additional information
Jam: https://jam.dev/c/18cb4bfc-9ada-407a-823a-50e93d005f4b

**Comment by ravilodhi** [comment]
The shipment method card defaults to the order ship group carrier and method, as the same is copied over to the shipment. If we change the carrier and method on the order ship group from the commerce UI after shipment creation, it won't affect the shipment carrier and method. However, if the carrier and method are changed from the shipment method card, it will also update the order ship group and shipment.

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.7.2. Hence, closing it.
