### ISSUE TITLE
Carrier is showing as C807 instead of the original order's carrier in the Shipment method card "In Progress" tab

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#702]
## Current behavior
The shipment carrier is incorrectly displayed as C807 instead of the correct one.

## Expected behavior
The shipment carrier should be displayed correctly according to the actual shipment carrier associated with the order.

## Steps to reproduce the issue
1. Navigate to the Order Detail page for any order.
2. Pick the order from the Order Detail page.
3. Observe the shipment carrier displayed after picking up the order.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [x] NO

## Environment details
- Browser: Chrome 127.0.6533.72
- OS: Mac OS (arm) 10.15.7
- Code Version: Dev environment of the fulfillment app

## Additional information
https://jam.dev/c/7dc493d1-ed4d-409f-b609-f70cc3aad1b5

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.8.0.
Hence, closing this issue.
https://jam.dev/c/dea8a3ac-ea1f-4bd2-8127-353f269e9a1f
