### ISSUE TITLE
Label Not Visible When Changing Carrier from Shipment Method Card and Clicking `Pack Order` Button

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#704]
## Current behavior
When changing the carrier from the shipment method card, the label is successfully generated and visible if done directly. However, if the carrier is changed from the card and the user clicks the `Pack Order` button instead, the label is not visible.

## Expected behavior
What is the expected behavior when the carrier is changed from the shipment method card? Should the label be generated automatically upon clicking the `Pack Order` button, or is the user expected to click `Generate Label`?

## Steps to reproduce the issue
1. Go to the shipment method card.
2. Change the carrier.
3. Click on the `Pack Order` button.
4. Observe that the label is not visible.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

**Comment by dt2patel** [comment]
Label should be auto generated upon clicking pack order. That function should not change because user now has option to select different shipping carrier

**Comment by ravilodhi** [comment]
@dt2patel 
Currently, when the 'Pack Order' button is clicked, the shipment is marked as packed. If a shipping label has already been auto-generated during the 'Pick Order' process or from the shipping method section of the order detail page, it is used, and printed along with the packing slip. However, the shipping label is not auto-generated when the 'Pack Order' button is clicked. 

Are we suggesting that the shipping label should be generated/regenerated if it hasn't been generated yet or voided when the 'Pack Order' button is clicked?

**Comment by dt2patel** [comment]
I see, we will need to factor in the following changes:

a pop up will need to be presented to the store staff that they need to enter tracking details. This will show up before the scan items popup if force scanning is enabled. Will provide more details in a doc shortly

<img width="507" alt="Screenshot 2024-08-22 at 5 50 30 PM" src="https://github.com/user-attachments/assets/6c34f810-1146-45a5-a872-92d721bde998">

**Comment by dt2patel** [comment]
https://docs.google.com/document/d/1Z5VeHa66jqRUpWq-HjuEbn8mXkcZghSlMSDiyNQDskU/edit?usp=sharing

Full implementation doc added here

**Comment by ymaheshwari1** [comment]
@Adameddy26 This issue is already available in v2.8.0 release, I think we can close this if everything is working as expected.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.10.4. Hence, closing this ticket.
