### ISSUE TITLE
Error message visibility issue in shipping label generation

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#725]
## Current behavior
When an error message is received from the carrier during shipping label generation, it does not immediately appear below the `ADD TRACKING CODE MANUALLY` button. A toast notification with the message `Failed to generate shipping label` is shown, but the detailed error message is not visible.

**Additional issues:**

1. When selecting a different carrier, the previous error message should be removed, but it persists.
2. If another carrier is selected and an error occurs again, the error message does not update. The user must close the details page and reopen it to view the updated error message.

## Expected behavior
1. The error message should be immediately visible below the `ADD TRACKING CODE MANUALLY` button when a shipping label fails to generate.
2. When switching to a different carrier, any previous error message should be cleared.
3. If a new error occurs with a different carrier, the error message should update without needing to close and reopen the details page.

## Steps to reproduce the issue
1. Attempt to generate a shipping label.
2. Observe that the error message is not visible below the `ADD TRACKING CODE MANUALLY` button.
3. Close the order details page in the app.
4. Again open the details page.
5. The error message is now visible.

## Additional information
Please have a look at the screen recordings to better understand the issue:
https://github.com/user-attachments/assets/9174ce32-8d05-47ff-ae83-bbec6297e8f1
https://github.com/user-attachments/assets/72229802-a21f-4ad5-90b2-99b5af9c4154

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.8.1. Hence, closing this ticket.
https://jam.dev/c/11550e94-11e6-42a7-9fe7-5c1f362710e3
