### ISSUE TITLE
Reject icon and inventory count misalignment

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#739]
## Current behavior
When the user clicks on the `Pack Item` button, the reject icon and the inventory count still appear in the card. These elements are shifted to the left of the card, causing a misalignment. 

## Expected behavior
The reject icon and inventory count should either disappear or stay aligned properly within the card after the `Pack Item` button is clicked.

## Steps to reproduce the issue
1. Click on the `Pack Item` button.
2. Observe the placement of the reject icon and inventory count.

## Additional information
Jam: https://jam.dev/c/58b9b6c4-b1cc-4604-8041-dc0bd7c97827

**Comment by ravilodhi** [comment]
This will be fixed under this - https://github.com/hotwax/fulfillment/pull/744

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.8.3. Hence, closing this issue.
