### ISSUE TITLE
Pass generateLabel flag as Y while retrying generating shipping label

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#745]
## Current behavior
Label is not getting generated if the facility is not part of auto generate label facility group even if retrying.

## Expected behavior
Label should be generated successfully.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Auto label generation enhancement changes are dependent on OMS release v5.16.0. Hence, marking this ticket as on-hold.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.1. Hence, closing this issue.
