### ISSUE TITLE
Order invoicing status card on order detail page

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#749]
## What is the motivation for adding/enhancing this feature?
To enhance the overall visibility of the invoicing status it's required to have a separate card to show the invoicing status.

## What are the acceptance criteria?
A card should be added to the order details page which shows the order invoicing status to the staff. When the order is sent to retail pro for invoicing, the response is logged into SOLR and is available to show on the UI.

Solr Detail:
coreName: logInsights
docType:ORDER_TO_INVOICE_API
fields: 
          status_txt_en (API Response Status)
          statusCode_txt_en (API Response Status Code)
          primaryEntity_txt_en (Primary Entity),
          primaryField_txt_en (Primary Field),
          response_txt_en (API Response Body),
          request_txt_en (API Request Body),
          createdDate_dt (createdDt)

Example: status_txt_en: success/failed
response_txt_en in case of failed:  {"Status":false,"Message":"The NoDocument in CustomerShipping field value is Null or empty"}
{"Status":false,"Message":"The DeliveryType Field has an Invalid Value"}

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

## Additional information
Reference Document - https://docs.google.com/document/d/16kVNInaNlGMFdiJuDzDbk36yrh6plEhY-egTYcibA0U/edit#heading=h.isl8d6totn69

**Comment by Adameddy26** [comment]
Enhancement changes verified and working fine in release v2.8.3. Hence, closing this ticket.
