### ISSUE TITLE
Remove `Generate Shipping Label` button from shipment method card on order details Page in `in-progress` tab

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#751]
**Description**:
Currently, there is an issue where users are click on the `Generate Shipping Label` button on the Shipment Method card before packing the item. This creates a problem because there is logic that adds the shipping cost to the first label generated before the item is packed. If the user clicks `Generate Label` without packing the item and the remaining items from the order are brokered to another facility, store associates at that facility may also generate a label, causing the shipping cost to be added multiple times.

**Proposed Solution:**
Remove the `Generate Shipping Label` button from the Shipment Method card on the order details page. This way, users will only be able to select the carrier, and the shipping label will only be generated once the item is packed, ensuring that shipping costs are added correctly and only once.

**Comment by AjinkyaM1** [comment]
@dt2patel sir should the button to generate the label also be removed from the Completed tab?

**Comment by dt2patel** [comment]
I guess not because there is no other option there.

**Comment by Adameddy26** [comment]
https://jam.dev/c/72cd5678-884e-4ff4-b524-0561b5d6ae1f

Enhancement changes verified and working fine in release v2.8.3. Hence, closing this ticket.
