### ISSUE TITLE
Add `Void Label` option on the Order Lookup Page

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#760]
## What is the motivation for adding/enhancing this feature?
We need to provide users with the ability to void shipping labels even after 24 hours of the order being processed. This feature should be accessible from the Order Lookup page, where tracking details are displayed.

## Feature Details:
1. Users should have the option to void the shipping label after 24 hours of the order being processed.
2. This action should trigger the label to be invalidated in the carrier system.

<img width="1430" alt="Screenshot 2024-09-14 at 9 24 02 AM" src="https://github.com/user-attachments/assets/2349a483-39d2-4807-bbd5-3dca07211be9">

**Comment by AjinkyaM1** [comment]
According to the latest comment from the client we will need to remove the void label functionality from the order look up page instead they want this on the OMS for the CSR team to void the label from there. They do not want stores to go in the order look up page and void the label.

**Comment by Adameddy26** [comment]
https://github.com/hotwax/fulfillment/issues/782
https://github.com/hotwax/fulfillment/issues/788

These two issues can be marked closed if requirement is going to be changed.
@amansinghbais Please look and take action.

**Comment by amansinghbais** [comment]
> #782 #788
> 
> These two issues can be marked closed if requirement is going to be changed. @amansinghbais Please look and take action.

Here we can close the #788 issue as we are removing the void functionality from the order lookup page. But the #782 issue still remains.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.3. Hence, closing this ticket.
