### ISSUE TITLE
Exclude cancelled TO order items

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#762]
## Current behavior
Currently if a TO order item is marked as cancelled, it still appears on the TO detail page and able to create a buggy shipment for the same.

## Expected behavior
Cancelled order items should not come.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Issue verified in release v2.9.0, and it was found that when a user attempts to search for a cancelled TO order item, it gets successfully scanned, and the "Create Shipment" option becomes enabled for the scanned item.
Hence, reopening this issue.
https://jam.dev/c/ee947a5c-fdea-453b-bb77-17933f8b401f

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.3. Hence, closing this issue.
