### ISSUE TITLE
Shipping lable not printing post generating shipping label while packing

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/fulfillment#764]
## Current behavior

When we generate shipping label using tracking code modal in pack button and try printing shipping label. The shipping label didn't come. Since order not updating post label generation.

## Expected behavior

SHould open shipping label and packing slip properly.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.0. Hence, closing this ticket.

**Comment by amansinghbais** [comment]
Same issue exist on the detail page, hence reopening this ticket.

**Comment by priyanshee1604** [comment]
The issue has been verified and is working correctly on the order detail page.
