### ISSUE TITLE
Picklist for TOs

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment#766]
## What is the motivation for adding/enhancing this feature?

Give option to print pick list for a TO

<img width="784" alt="Screenshot 2024-09-17 at 12 39 03 PM" src="https://github.com/user-attachments/assets/b24f3416-8915-411b-926c-d71f8a27cfe6">

**API:**
https://dev-oms/api/TransferOrder.pdf?orderId={transferOrderId}

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.3. Hence, closing this ticket.
