### ISSUE TITLE
Disable `Ship Now` button for ADOC to align with Retail Pro invoicing flow

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#769]
## What is the motivation for adding/enhancing this feature?
Currently, the `Ship Now` button is enabled for orders in ADOC. This poses a concern for the client, as the order's invoicing in Retail Pro is confirmed only when Retail Pro hits the NiFi endpoint, at which point the order is also marked as completed. The client is worried that store associates might click the `Ship Now` button before the order is automatically shipped upon Retail Pro hitting our endpoint.

**Background**:
1. The current flow involves Retail Pro hitting the NiFi endpoint to confirm invoicing, which simultaneously marks the order as completed.
2. If the `Ship Now` button remains enabled, there's a risk that orders could be manually shipped before this automated process.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.0. Hence, closing this ticket.
