### ISSUE TITLE
New shipping label generated after manually entering incorrect tracking code

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#775]
## Current behavior
A new shipping label is generated and displayed when a tracking code is manually entered and saved.

## Expected behavior
No new shipping label should be generated when a tracking code is entered manually. The system should display the existing label associated with the selected carrier and shipment method.

## Steps to reproduce the issue
Go to the 'In Progress' tab and open the order detail page of an order.
Click pack order button.
Select the carrier and shipment method.
Manually enter the tracking code for the order.
Save the tracking code.
View label for the selected carrier and shipment method.
Observe the issue.

## Environment details
App version : v2.9.0
App environment : UAT

## Additional information
https://jam.dev/c/8a241f4c-e0f1-4dae-b08c-5384a370cca3

**Comment by amansinghbais** [comment]
This issue is fixed was fixed in the following PR: https://github.com/hotwax/fulfillment/pull/773

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.10.0. Hence, closing it.
