### ISSUE TITLE
Add carrier name next to tracking code and implement tracking URL for supported carriers

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#777]
## What is the motivation for adding/enhancing this feature?
Enhance the order tracking information by displaying the carrier name next to the tracking code and providing a tracking URL for supported carriers in the order look up page.

## Requirements:

1.  Append the carrier name to the tracking code in the following format 
         Tracking Code: 532281899 - CityExpress
2. The tracking URL, at least for the carriers that provide this feature (like C807).

 **Additional information** 
 Clickup ticket for reference: https://app.clickup.com/t/86cvzt9cc

**Comment by Adameddy26** [comment]
Verified in release v2.10.0 and found that the tracking URL for C807 is not clickable. Hence, reopening this issue.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.11.4. Hence, closing this issue.
https://jam.dev/c/9deb4624-5545-4d8e-b4ab-55f8df208a1b
