### ISSUE TITLE
Tracking code visible in Order Lookup details after label is voided

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#788]
## Current behavior
The tracking code remains visible in the Order Details, even though the label has been voided.

## Expected behavior
The tracking code should either be removed or marked as voided in the Order Details once the label is voided.

## Steps to reproduce the issue
Navigate to the Order Lookup section and open the Order Details for an order.
Void the label associated with the order.
Observe that the tracking code is still visible.

## Environment details
App version : v2.9.1
App environment : UAT

## Additional information
https://jam.dev/c/8adc1b5e-fe02-4605-8eae-42e4e8bcbb9e

**Comment by amansinghbais** [comment]
Closing this ticket as not relevant because the void button is not required anymore in the order lookup page.
https://github.com/hotwax/fulfillment/issues/760
