### ISSUE TITLE
Prevent displaying StorePickup option in the fulfillment app

### ISSUE THREAD

**Issue by suranands-1940824** [hotwax/fulfillment#790]
## Current behavior
In the Production and UAT environment of the fulfillment app the following is happening:

1) The 'Pack Order' Modal allows for store staff to change the shipping method to STORE PICKUP.

2) Behavior (1) can be reproduced in the 'View Details' page as well.

3) In the 'View Details' page of the fulfillment app, the 'Shipment method' card allows store staff to generate shipping label for STORE PICKUP. 

## Expected behavior

The STORE PICKUP shipping method should not be displayed in the fulfillment app in the 'Pack Order' Modal or the 'Shipment Method' card. This has to be fixed both ion UAT and OMS.

### Behavior 1
1) Go to the 'In Progress' Tab of the fulfillment app.
2) For an order, click on the 'Pack' button to open the 'Pack Order' Modal.
3) Choose 'Default' from the 'Carrier' dropdown.
4) Choose 'Store Pickup' from the 'Method' dropdown.
5) Enter a random tracking code in the 'Tracking code' field.
6) Click on the save icon.

### Behavior 2
1) Go to the 'In Progress' Tab of the fulfillment app.
2) For an order, click on the chip showing the order ID.
3) Click on the 'View Details' option.
4) Click on the 'Pack order' button.
5) Choose 'Default' from the 'Carrier' dropdown.
6) Choose 'Store Pickup' from the 'Method' dropdown.
7) Enter a random tracking code in the 'Tracking code' field.
8) Click on the save icon.

### Behavior 3
1) Go to the 'In Progress' Tab of the fulfillment app.
2) For an order, click on the chip showing the order ID.
3) Click on the 'View Details' option.
4) Under the 'Shipment Method' card choose 'Default' from the 'Carrier' dropdown.
5) Choose 'Store Pickup' from the 'Method' dropdown.

## Can you handle fixing this bug by yourself?

- [ ] NO

## Environment details
App version: v2.8.1
App environment: UAT

## Additional information
Goal is to hide the Store Pickup option from the fulfillment app as it does not make sense for it to be there.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.3. Hence, closing this ticket
