### ISSUE TITLE
Add Invoicing Facility to additional details card in the Order Lookup Page

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#796]
## What is the motivation for adding/enhancing this feature?
We need to enhance the order lookup page by adding an invoicing facility to the "Additional Details" card. This will allow users to easily view the Invoicing facility of the order directly from the order lookup page.

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.3 .Hence, closing this ticket.
