### ISSUE TITLE
Latest payment transaction not displaying in Fulfillment App's Order Card

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#797]
## Current behavior
In the fulfillment app, on the Order Details page, the payment transaction shown on the order card is not reflecting the latest transaction. Instead, it continues to display the first payment transaction, even though a new transaction has been captured. Additionally, if the first payment transaction is deleted, the status updates, but the latest payment transaction still does not appear on the order card.

## Expected behavior
The latest payment transaction should always be displayed on the order card in the fulfillment app's Order Details page.

## Steps to reproduce the issue
1. Place an order and complete a payment on Shopify (e.g., using Cash on Delivery).
2. Capture a second payment transaction in Shopify, which should update in OMS.
3. In the fulfillment app, navigate to the View Details page for the order.
4. Observe that the order card continues to display the first payment transaction instead of the latest one.
5. Delete the first payment transaction and check whether the latest payment is displayed (it will not show up).

## Additional information
https://adoc-sv-uat.hotwax.io/commerce/control/ViewOrder?orderId=HP13161
<img width="1440" alt="Screenshot 2024-09-30 at 11 14 47 AM" src="https://github.com/user-attachments/assets/fcf58c5f-e7bf-4651-b2a9-1bc941ba2f23">

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.9.3. Hence, closing it.
