### ISSUE TITLE
Disable Save Button in 'Add Tracking Code' Modal on pack When No Shipment Methods Are Available

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/fulfillment#805]
## What is the motivation for adding/enhancing this feature?

Currently user can pack the order without having shipment methods for a career on changing career in the generate tracking code modal. This happens in case when isTrackingRequired is "N"

- We should disable the save button, if no shipmentMethods are available for the selected carrier.
- Also sort the payment record in the order lookup in order of recent to oldest.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.10.0. Hence, closing this issue.
