### ISSUE TITLE
Show message on login error page in case of login failure and dismiss loader on issue in facility change due to no product store

### ISSUE THREAD

**Issue by amansinghbais** [hotwax/fulfillment#807]
## What is the motivation for adding/enhancing this feature?

- Should show user a message on screen when unable to login due to no product store available for current facility.
- Should dismiss loader and not change facility if no store associated with that facility.

## What are the acceptance criteria?

- [ ] ...

## Can you complete this feature request by yourself?

- [ ] YES
- [ ] NO

**Comment by Adameddy26** [comment]
Issue verified and working fine in release v2.10.0. Hence, closing this ticket.
