### ISSUE TITLE
Order Record Not Updated on Picking or Unpacking the Order

### ISSUE THREAD

**Issue by Adameddy26** [hotwax/fulfillment#812]
## Current behavior
The order remains in the Open tab after picking.
The order remains in the Completed tab after unpacking.

## Expected behavior
On picking an order, it should move from Open to In Progress.
On unpacking an order, it should move from Completed to In Progress.

## Steps to reproduce the issue
Pick an order from the Open tab.
Check if the order moves to the In Progress tab.
Unpack an order from the Completed tab.
Check if the order moves to the In Progress tab.

## Environment details
App version: v2.9.3
App environment : Uat

## Additional information
https://jam.dev/c/79c4b4c7-95b3-4ed1-b461-78516a73236b

**Comment by dt2patel** [comment]
@amansinghbais is this most likely because of SOLR not being updated in Real time? Requires reload on user's side?

**Comment by ymaheshwari1** [comment]
Yes, we can close this.

**Comment by ymaheshwari1** [comment]
Closing this as its related to SOLR indexing and this issue is only on dev/uat envs.
