### ISSUE TITLE
Option to hide rejection reasons from fulfillment app.

### ISSUE THREAD

**Issue by dt2patel** [hotwax/fulfillment#813]
## What is the motivation for adding/enhancing this feature?

<img width="974" alt="Screenshot 2024-10-13 at 10 08 00 PM" src="https://github.com/user-attachments/assets/b7cbd6ff-3fc1-4626-b09b-80f09c6b1821">

Logic:
https://docs.google.com/document/d/1c5UjqxxP2HfkDHr4CgAQJEoCTlbPtlcaiguw87Mpxn8/edit

**Comment by Adameddy26** [comment]
Verified and working fine in release v2.10.6. Hence, closing this ticket.
