### ISSUE TITLE
Enable void label until order is in the completed tab

### ISSUE THREAD

**Issue by AjinkyaM1** [hotwax/fulfillment#870]
## What is the motivation for adding/enhancing this feature?
Currently, when an order is shipped, the `Void Label` button gets disabled. However, users should still be able to void the label after shipping the order. Therefore, we need to keep the `Void Label` button enabled as long as the order remains in the fulfillment app.

**Comment by priyanshee1604** [comment]
Verified that the user can void the label even after the order has been shipped, ensuring that the Void Label button remains enabled.
