### ISSUE TITLE
Label Image Url not opening in new tab if the url doesn't contains .pdf extension

### ISSUE THREAD

**Issue by ravilodhi** [hotwax/fulfillment#873]
## Current behavior
Currently if the ShipmentPackageRouteSeg.labelImageUrl is opened in new tab only when it contains .pdf extension.

## Expected behavior
If the ShipmentPackageRouteSeg.labelImageUrl contains data then always open it directly in new tab.

## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Code Version:

**Comment by priyanshee1604** [comment]
Verified that when the labelImageUrl is opened with an extension other than .pdf, it still opens in a new tab. Hence, the functionality is working correctly.
